---
title: "Pumpkins Challenge Report"
subtitle: "LIFE4138"
author: "Caleb Thornber"
toc: true
html:
 code-overflow: wrap
---

## Modules
For the script 6 modules where imported.
```{python}
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colormaps
import seaborn as sns
import csv 
```

## Aditional Code
```{python}
output = open('output.txt', 'w')
```
Creates a .txt file named output. This is for any text information which will be generated by the script to go to.
## Question 1 - Read in the Data Set

```{python}
def import_csv(file):
	"""
	Imports a .csv file into a pandas data frame, to allow error handling

	Args:
	file (str) - name of file wanting to import

	Output:
	Returns file as object ready to assing
	"""
	try:
		df = pd.read_csv(file)
		return df
	except pd.errors.EmptyDataError:
		print("####ERROR import_csv: File is not a .csv. Cannot be read####")
		print("####                  Quitting program                  ####")
		quit() 
	except FileNotFoundError:
		print("####ERROR import_csv: File not found. Cannot be read####")
		print("####                 Quitting program               ####")
		quit() 
```

The .csv file is read into the script and assigned to the object pumpkins. the pandas function `read_csv()` is used. `df` is a data frame which is returned and assigned to `pumpkin` in the main body.

```{python}
pumpkin = import_csv("pumpkins_08.csv")
```

#### Error Handlng
`pd.errors.EmptyDataError`

* If the file being tried to read is not a .csv the program will end

`FileNotFoundError`

* If the file does not exist the program will end

## Question 2 - Identifying the Heaviest Pumpkin
```{python}
#| code-overflow: wrap

try:
  heaviest = pumpkin.loc[pumpkin['weight_lbs'].idxmax()] # Returns row of heaviest pumpkin

  output.write(f"The heaviest pumkin was in {str(heaviest['id'])[:4]}. Variety: {heaviest['variety']}, Location: {heaviest['city']}, {heaviest['country']}.\n\n")	
		# ^^^ Prints information. Takes first 4 characters of id for the year
		
except KeyError as e:
	print("####ERROR main (find heaviest): a/multiple provided args do not exist.####")
	print("####    Unable to get mean, Error message returned    ####\n")
	output.write("####ERROR main (find heaviest): a/multiple provided args do not exist.####")
	output.write("####    Unable to get mean, Error message returned    ####\n\n")
except AttributeError as e:
	print("####ERROR main: (find heaviest) Trying to locate in a none df object####\n")
	output.write("####ERROR main (find heaviest): Trying to locate in a none df object####\n")
```

`pumpkin['weight_lbs'].idxmax()`returns the entire row for the highest value within the column `weight_lbs`. Using `idxmax()` will return the row id for the heaviest pumpkin, as apposed to the value itself.

`pumpkin.loc[]` takes the row id found by `idxmax()` and returns the entire row from within `pumpkin`. This row is assigned to `heaviest`. Assigning the row to an object allows for less cumbersome outputting of the df. It allows for each part of the row to be extract from the object as opposed to from the df set each time. 

The output is the written to an output.txt file (see Additional Code).

The year was extracted from the `id` column. This was formatted as 'YYYY-XX' where YYYY was the year and XX was a number. The first 4 characters were taken to show the year. All other values were returned as found.

Outputs:

* Writes information about heaviest pumpokin to `output.txt`

#### Error Handling
`KeyError`

* If a key does not exist, an error message is printed to the terminal and written to `output,txt`

`AttributeError`

* If the object being read is not a df frame, an error message is printed to the terminal and written to `output,txt`

## Question 3 - Converting lbs to kg
```{python}
def lbs_to_kg(df, col, new_col = 'new_column'):
	"""
	Converts weights in a column which are in lbs into kg

	Args:
	df - Dataset to look in
	col - Column wanting to convert
	new_col - name of new column for conversion df to go

	Output
	Adds a new column with converted weights
	"""

	try:
		df[new_col] = (df[col]*0.4536) #Creates weights_kg column, converts lbs to kg and adds it in
	
		return df #Returns df with new_col

	except KeyError as e:
		print(f"####ERROR lbs_to_kg: a/multiple provided args do not exist####")
		print(f"####Args: {e.args}####\n")
		return None
	except TypeError:
		print("####ERROR lbs_to_kg: col does not contain int/float####")
		print("####        	  new_col not created              ####\n")
		return None
```

`lbs_to_kg` converts values within a column whihc are in pounds into kilograms. It adds them to a new column within the df frame.

Inputs:

* `df` (data frame) - The dataset where the a the conversion is needed
* `col` (str) - Name of the column wanted to be converted
* `new_col` (str) - Name of the column you want converted values to be put into

The `col` is multiplied by 0.4564. The values were assigned to `new_col` within `df`. `df` is returned out of the function with the new df in `new_col`.

Outputs:
* A new column with converted values

In the script the function was used as below:
```{python}
lbs_to_kg(pumpkin, 'weight_lbs', 'weight_kg')
```
A new column named 'weight_kg' was created containing converted values from `weight_lbs` from within `pumpkin`.

#### Error Handling
`KeyError`

* If an arg passed in does not exist `None` is returned

`TypeError` 

* If `col` does not contain an int or float, `None` is returned

## Question 4 - Creating Weight Classes
```{python}
def classify(df, col, new_col, classes = [0, 1, 2]):
	"""
	Adds a new column with classes for a chosen column

	Args:
	df (data frame) - Dataset to look in
	col (str) - Column wanting to classify
	new_col (str) - name of new column to add classes in
	classes (list) - Classes wanted to be assigned in new_col. Must be length of 3 

	Output
	Adds a new column to df with classes. Returns the new dataset
	"""
	try:
		mean = df[col].mean() #Calculates mean of weights in kg
		sd = df[col].std() #Calculates standard deviation of weights in kg
		df[new_col] = '' #Creates new column 
		

		for i in range(len(df[col])): #Loops through the weight_kg column
		
			if df[col][i] < (mean - sd): #Selects rows with weight = mean-sd
				df.iloc[i, df.columns.get_loc(new_col)] = classes[0] #Adds first value class to new_col
			
			elif df[col][i] > (mean + sd): #Selects rows with weight = mean+sd
				df.iloc[i, df.columns.get_loc(new_col)] = classes[2] #Adds 3rd value of class to new_col

			elif math.isnan(df[col][i]) == True:
				df.iloc[i, df.columns.get_loc(new_col)] = np.nan

			else:
				df.iloc[i, df.columns.get_loc(new_col)] = classes[1] #Else, rest get 2nd value of class added to weight_class column

		return df

	except TypeError:
		print("####ERROR classify: col is not int/float####")
		print("####      df returned unchanged       ####\n")
		return df
	except KeyError as e:
		print("####ERROR classify: a/multiple provided args do not exist####")
		print("####                df returned unchanged              ####")
		print(f"####Args: {e.args}####\n")
		return df
	except AttributeError:
		print("####ERROR classify: Cannot pull from df as not a df frame####")
		print("####                      Returned None                      ####\n")
		return None

```
The function `classify()` was created to allow the addition of any classes to the df set as needed. The function assigns a high class as o1 or more standard deviations above the mean, and the low class as 1 or more standard deviations below the mean. The middle class is with that range.

Inputs:

* `df` (data frame) - The dataset which you want the function to run on
* `col` (str) - The column within df which you want the classification bassed on 
* `new_col` (str) - The name of the new column you want the classed adding into
* `classes` (list) - A list of 3 strings, which you want the classes to be named. Value 0 is the lower class, 1 is the middle class and 2 is the upper class

The mean and standard deviation of `col` was calculated with the `mean()` and `std()` functions from within `numpy`.
A blank new column is created.
A for loop with the length of `col` allows for iteration for each value in the list. This assigns each value individually so it can be slow on large data sets.

`if` and `elif` functions are used to check if the current value is below, or above 1 standard deviation from the mean. `else` is used to assign values within that range.

`iloc` is used to provide the location with df for the class to be assigned. It gets assiged to row i. The column is found through `df.columns.get_loc(new_col)`. This returns the numerical id for `new_col` so it can be assigned with `iloc`

Class names get pulled from the list. `classes`.

Outputs:

* `df[new_col]` - A new column within `df`, which contains the classes provided in the function

Within the script the function was ran as below.
```{python}
classify(pumpkin, 'weight_kg', 'weight_class', ['light', 'medium', 'heavy'])
```
Here `pumpkin` gets a new column added to it named 'weight class'. It classifies each row as 'light', 'medium', or 'heavy' based on the column `weight_kg`. Classes were made according to standard distributions, as when plotted in question 5, it can better show the drstribution of the df.

#### Error Handling
`TypeError`

* If `col` does not contain an int or float, `df` is returned unchanged

`KeyError`

* If a arg passed into `classify()` does not exist, `df is returned unchanged

`AttributeError`

* If `df` is not a df frame, `None` is returned

## Question 5 - Plotting Estimated and Actual Weights
```{python}
#| fig-cap: "**Figure 1**: A scatter graph plotting the recorded weights of pumpkins against their estimated weights in kilograms. All values in estimated weight which are zero were removed. Points are coloured according to their weight class. Light pumpkins are one standard deviation below the mean, heavy pumpkins are more than one standard deviation above the mean. Medium pumpkins are within these two values."

try:
	pumpkin['est_weight'] = pumpkin['est_weight'].replace({0:np.nan}) #Sets 0 values to NaN within 'estimated_weight'
	
except Exception as e:
	print("####ERROR main (remove 0): a/multiple provided args are unable to be read.####")
	print(f"####Args: {e.args}####\n")

lbs_to_kg(pumpkin, 'est_weight', 'est_weight_kg') #Creates new column with converted weights named 'est_weight_kg'

try:
	fig1 = sns.scatterplot(
		x='est_weight_kg', y='weight_kg', #Sets axis
		hue='weight_class', #Colours by class
		data=pumpkin) #Data is pumpkins dataset
	plt.title('A scatter graph of Estimated Weight vs Recorded Weight') #Gives title
	plt.xlabel('Estimated weight/kg') #Labels x-axis
	plt.ylabel('Recorded weight/kg') #Labels y-axis
	plt.legend(title='Weight Class') #Gives title to legend
	plt.savefig('Figure_1.png') #Saves plot to png

except Exception as e:
	print(f"####ERROR Fig1: Trying to plot none correct df####")
	print(f"####{e.args}####\n")
```
For the plot I chose to remove all zero values from `est_weight`. This is as the values are likely to be missing df points, and as such appear as zero in the df set. It is likely that not every grower in the competitions were able to get estimated weight df. I interogated this by using `filter_col()` (see question 6), as below, to select only pumpkins with zero estimated weights. Zero values in `est_weight` were replaced with `nan` from `numpy` using `replace`. 

```{python}
#| eval: false
filter_col(pumpkin, 'est_weight', [0], 'pumpkin_0_est')
```

Here many pumpkins also lack df for `ott`, `pct_chart`, `polinator_mother`, and `pollinator_farther`. This suggests that the zero values come from a lack of df, as opposed an actual estimated weight of 0.

In order to plot the graph in kg, the `est_weight` was put through `lbs_to_kg()` to create a column containing the estimated weights of the pumpkins in kg. It was ploted as a seaborn scatterplot using `sns.scatterplot`. All other attributes were assigned through pyplot.

The graph identified that most pumpkins' actual weights were clost to their estimated wheights. However there was a notable outlier with a estimated weight of 4430 kg, with an actual weight of 678 kg. It is possible that there is order-of-magnitude error, as an estimated weight of 443 kg fits more closely with the rest of the df.

This df point was evaluated with the code below.

```{python}
#| eval: false
print(pumpkin.loc[pumpkin['est_weight_kg'].idxmax()])
```

#### Error Handling
`Exception`

* If any errors arise, an error message is returned and NaN's are not set to 0 it states the arg causing the error. Both have the same error handling. Seperate to help locate the error

## Question 6 - Filtering Data
```{python}
def filter_col(df, col, filt = [], file_name='filter_output'):
	"""
	Creates filtered .csv file for pumpkins for chosen filters

	Args:
	df (data frame)- Dataset to look in
	col (str) - Column to filter by
	filt (list) - Selected items to filter for
	file_name (str) - Chosen name for file to be outputed. Does not require .csv extention

	Output:
	.csv - Contains only pumpkin df from chosen countries
	"""
	try:
		df_filtered = pd.DataFrame(columns=list(df.columns.values)) #Creates blank df frame with same 

		for i in range(len(filt)): #For loop iterates through all items in filt.
			df_filtered = df_filtered._append(df[df[col] == filt[i]]) #Adds all rows contain item i in filt into the blank df frame

		df_filtered.to_csv(file_name+'.csv', sep=',', index=False, header=True) #Exports the df frame as a .csv file

		return df_filtered

	except KeyError as e:
		print("####ERROR filter_col: a/multiple provided args do not exist.####")
		print("####       Unable to filter, df returned unflitered       ####\n")
		print(f"####Args: {e.args}####")
		return df
	except TypeError as e:
		print("####´ERROR filter_col: col does not contain int/float.####")
		print("####    Unable to filter, df returned unflitered    ####\n")
		return df
	except AttributeError:
		print("####ERROR filter_col: Cannot pull from df as not a df frame####")
		print("####                        Returned None                      ####\n")
		return None
```
`filter_col()` produces a new .csv file, containing only rows, filtered by specified values.

Inputs:

* `df` (data frame) - df frame that wants to be filtered
* `col` (str) - Name of the column which is filtered by
* `filt` (list) - Contains the values you want to filter for (keep)
* `file_name` (str) - Chosen name of the exported .csv file. Does not require the .csv extension

A blank df frame (`df_filtered`) is created with the headings of `df`.

A for loop the length of the provided filters is used to go through the data set individually for each filter.

`_append` adds all rows from `df` where the value in `col` is equal to filter number i. The next iteration of the for loop will check for the next filter. 

The new df frame `df_filtered` is written to a .csv file with the name provided. It is also returned out of the function and assigned to `pumpkin_filtered`.

In the script `filter_col()` was ran as below.
```{python}
pumpkin_filtered = filter_col(pumpkin, 'country', ['Spain', 'Japan', 'France'], 'pumpkins_filtered')
```

#### Error Handling
`KeyError`

* If an arg does not exist, a message is printed and the arg is stated. `df` is returned unchanged

`TypeError`

* If col does not contain int or float df, `df` is returned unchanged and an error message is printed

`AttributeError`

* If `df` is not a df frame, `None` is returned and an error message is printed

## Question 7 - Summarise by Country and Variety
```{python}
def summary_mean(df, col, groups):
	"""
	Summarises df by selected groupings and operation

	Args:
	df (data frame) - Dataset to summarise
	col (str) - Column in df to summarise
	group (list) - Columns to summarise by. First vaule is the main column, gives individual sumary.

	Output:
	Table with df for country and variety
	"""
	try:
		summ1 = str(df.groupby(groups[0])[col].mean()) #Prints summary
		if len(groups) > 1: #Checks if more than one value is in groups. If yes, provides the multiple summary
			summ2 = str(df.groupby(groups)[col].mean()) #Prints multiple summary
			return f"{summ1}\n\n{summ2}"
		else:
			return summ1

	except KeyError as e:
		print("####ERROR filter_col: a/multiple provided args do not exist.####")
		print("####      Unable to get mean, Error message returned        ####")
		print(f"####Args: {e.args}####\n")
		return "####ERROR filter_col: a/multiple provided args do not exist.####\n\n"
	except TypeError as e:
		print("####ERROR filter_col: col provided does not contain int/float.####")
		print("####       Unable to get mean, Error message returned         ####")
		print(f"####Args: {e.args}####\n")
		return "####ERROR filter_col: col provided does not contain int/float.####\n\n"
	except AttributeError:
		print("####ERROR filter_col: Cannot pull from df as not a df frame####\n")
		print("####                        Returned None                      ####")
		return None
```
`summary_mean()` will provide mean and grouped mean of a column of choice, and it will group it by specified groups. The first column will give an individual summary for that column. And other columns will provide a combined summary. 

Inputs:

* `df` (data frame) - Data set to summarise
* `col` (str) - Column in df to summarise
* `group` (list) - Columns to summarise by. First vaule is the main column, gives individual summary.

The mean df, grouped by the first column in `groups`, is assigned to `summ1` as a string. The function checks if there are more than one column to summarise by. If yes it will assigned the combined summary to `summ2` as a string. `summ1` and `summ2` are returned in a concatenated formatted with a blank line between them. If there is only 1 column in `groups` it returns `summ1`.

The output of `summary_mean()` will is assined to the object `summary_out`. It is then written to `output.txt`.
```{python}
summary_out = summary_mean(pumpkin_filtered, 'weight_kg', ['country'])
output.writelines(summary_out)
```

#### Error Handling

`KeyError`

* If an arg does not exist, an error message is returned. It is printed to the terminal and `output.txt`

`TypeError`

* If col does not contain int or float df, an error message is returned. It is printed to the terminal and `output.txt`

`AttributeError`

* If `df` is not a data frame, `None` is returned

## Question 8 - Plotting the Filtered Data
```{python}
#| fig-cap: "**Figure 2**: A boxplot showing the distribution of pumpkin weights of the filtered countries in kg."
try:
	fig2 = pumpkin_filtered.boxplot(column='weight_kg', by='country', grid=False) #Generates boxplot without a grid
	plt.title('A Boxplot of 3 countries and the Weights of Pumpkins') #Gives title
	plt.ylabel('Country') #Labels x axis
	plt.xlabel('Weight/kg') #Labels y axis
	plt.savefig('Figure_2.png') #Saves as png

except Exception as e:
	print(f"####ERROR Fig2: Trying to plot none correct df####")
	print(f"####{e.args}####\n")
```
A boxplot for the 3 countries is created using `pyplot` from `matplotlib`. It graphs the df from `weight_kg`, and groups it by `country`. It uses data from `pumpkin_filtered`, so only countries selected in `filter_col` are included.

The plot is titled and labelled as above. It is saved to a .png titled "Figure_2".

#### Error Handling 

`Exception`

* If any error occurs an error messgae shows. The arg causing the error is printed
### Question 9 - Faceted Box Plot of the Filtered Data
```{python}
#| fig-cap: "**Figure 3**: A faceted box plot grouped by countries selected from the filter function. Each plot shows the distribution of weights in kilograms by their variety."
try:
	fig3 = sns.FacetGrid(pumpkin_filtered, #Data taken from pumkin_filtered and produces facet grid
		col='country', #Facets the df by country
		hue='variety', #Colours boxplots by pumpkin variety
		height=6, aspect=0.75, #Sets size of the axis
		palette='tab20') #Sets colour for hue
	fig3.map_dataframe(sns.boxplot, 'variety', 'weight_kg') #Creates the boxplots using seaborn
	fig3.fig.suptitle('Boxplots of Variety Against Weights, Grouped by Country') #Gives title
	fig3.set_titles(col_template='{col_name}', row_template='{row_name}') #Labels facet grid row and column
	fig3.set_axis_labels('Variety', 'Weight/kg') #Labels axis
	fig3.set_xticklabels(rotation=90) #Writes x axis tick lables vertically
	fig3.figure.tight_layout(rect=[0,0,1,0.95]) #Gives more room for plot
	plt.savefig('Figure_3.png') #Saves as png

except Exception as e:
	print(f"####ERROR Fig3: Trying to plot none correct df####")
	print(f"####{e.args}####\n")
```
Seaborn was used to created the faceted plot of the countries by variety.

A facet grid for the countries was created by `sns.FacetGrid()`. The df is taken from `pumpkin_filtered` and the facets are split by country. `hue` is set as `variety` to colour each box on the plot. The colour palette for `hue` was selected as `tab20` due to the number of varieties requiring several colours.`height` and `aspect` set the size of the size of the facet axis to make it more readable.

* `map_dataframe` with `sns.boxplot` applies a boxplot to the facets. 
* `fig.suptitle` gives the whole facet plot a title
* `set_titles` titles the rows and columns of the facet
* `set_axis_labels` adds labels to the axis
* `set_xticklabels` rotates x tick labels 90 º to make them readable
* `tight_layout` adjusts plot to fit the title
* `savefig` saves the figure as a png

#### Error handling
`Exception`

* If any error occurs an error messgae shows. The arg causing the error is printed
### Question 9 - Faceted Box Plot of the Filtered Data